# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: opengov-util 2.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "opengov-util"
  s.version = "2.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Tim Rodriguez"]
  s.date = "2017-02-12"
  s.description = "Useful utilities for Ruby"
  s.email = ["trodriguez@opengov.com"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".rspec",
    ".rubocop.yml",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "VERSION",
    "lib/core_ext/hash.rb",
    "lib/opengov/util.rb",
    "lib/opengov/util/collection.rb",
    "lib/opengov/util/collection_methods.rb",
    "lib/opengov/util/default_hash.rb",
    "lib/opengov/util/errors.rb",
    "lib/opengov/util/fog_dynamodb_20120810.rb",
    "lib/opengov/util/identity_lookup.rb",
    "lib/opengov/util/lazy_collection_enumerator.rb",
    "lib/opengov/util/lookup_hash.rb",
    "lib/opengov/util/nested_hash.rb",
    "lib/opengov/util/query_params.rb",
    "lib/opengov/util/thread_pool.rb",
    "opengov-util.gemspec",
    "spec/core_ext/hash_spec.rb",
    "spec/lib/collection_spec.rb",
    "spec/lib/common_collection_examples.rb",
    "spec/lib/default_hash_spec.rb",
    "spec/lib/identity_lookup_spec.rb",
    "spec/lib/lookup_hash_spec.rb",
    "spec/lib/nested_hash_spec.rb",
    "spec/lib/query_params_spec.rb",
    "spec/lib/thread_pool_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "https://github.com/OpenGov/og-ruby-utils"
  s.licenses = ["MIT License"]
  s.required_ruby_version = Gem::Requirement.new(">= 2.0.0")
  s.rubygems_version = "2.4.5"
  s.summary = "OpenGov Ruby Utilities"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ruby_dig>, [">= 0"])
      s.add_runtime_dependency(%q<concurrent-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<concurrent-ruby-ext>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<rubocop>, [">= 0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
    else
      s.add_dependency(%q<ruby_dig>, [">= 0"])
      s.add_dependency(%q<concurrent-ruby>, [">= 0"])
      s.add_dependency(%q<concurrent-ruby-ext>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<rubocop>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
    end
  else
    s.add_dependency(%q<ruby_dig>, [">= 0"])
    s.add_dependency(%q<concurrent-ruby>, [">= 0"])
    s.add_dependency(%q<concurrent-ruby-ext>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<rubocop>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
  end
end

